# Generated by Django 5.0.1 on 2026-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_type", models.CharField(max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                (
                    "search_to_booking_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("page_views_before_booking", models.IntegerField(default=0)),
                ("searches_before_booking", models.IntegerField(default=0)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("referrer", models.URLField(blank=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Booking Analytics",
                "verbose_name_plural": "Booking Analytics",
                "db_table": "booking_analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("car", "Car Rental"),
                            ("restaurant", "Restaurant"),
                            ("attraction", "Attraction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(blank=True, db_index=True, max_length=200)),
                (
                    "destination",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("results_count", models.IntegerField(default=0)),
                ("search_duration_ms", models.IntegerField(default=0)),
                ("clicked_results", models.JSONField(blank=True, default=list)),
                ("converted_to_booking", models.BooleanField(default=False)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Search Analytics",
                "verbose_name_plural": "Search Analytics",
                "db_table": "search_analytics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("search_flight", "Search Flight"),
                            ("search_hotel", "Search Hotel"),
                            ("view_flight", "View Flight"),
                            ("view_hotel", "View Hotel"),
                            ("create_booking", "Create Booking"),
                            ("payment", "Payment"),
                            ("create_review", "Create Review"),
                            ("create_itinerary", "Create Itinerary"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "db_table": "user_activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
