# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("primary_traveler_name", models.CharField(max_length=255)),
                ("primary_traveler_email", models.EmailField(max_length=254)),
                ("primary_traveler_phone", models.CharField(max_length=20)),
                ("special_requests", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("cancellation_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-booking_date"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("car", "Car Rental"),
                            ("attraction", "Attraction"),
                            ("restaurant", "Restaurant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("item_name", models.CharField(max_length=500)),
                ("item_description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("item_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bookings.booking",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Item",
                "verbose_name_plural": "Booking Items",
                "db_table": "booking_items",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="BookingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Status",
                "verbose_name_plural": "Booking Status History",
                "db_table": "booking_status_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "-booking_date"], name="bookings_user_id_dca47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_number"], name="bookings_booking_502bea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "-booking_date"], name="bookings_status_c7bea3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingitem",
            index=models.Index(
                fields=["booking", "item_type"], name="booking_ite_booking_7e90c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingitem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="booking_ite_content_5870f1_idx",
            ),
        ),
    ]
