# Generated by Django 5.2.12 on 2026-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("flight", "Flight"),
                    ("hotel", "Hotel"),
                    ("rental", "Vacation Rental"),
                    ("car", "Car Rental"),
                    ("attraction", "Attraction"),
                    ("restaurant", "Restaurant"),
                ],
                max_length=20,
            ),
        ),
    ]
