# Generated by Django 5.2.12 on 2026-04-16 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("friend", "Friend"),
                            ("family", "Family"),
                            ("colleague", "Colleague"),
                            ("other", "Other"),
                        ],
                        default="friend",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "invite_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(blank=True, max_length=36, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_contacts",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "city"], name="user_contac_owner_i_b175f9_idx"
                    )
                ],
            },
        ),
    ]
