# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_booking_updates", models.BooleanField(default=True)),
                ("email_payment_updates", models.BooleanField(default=True)),
                ("email_price_alerts", models.BooleanField(default=True)),
                ("email_itinerary_updates", models.BooleanField(default=True)),
                ("email_promotional", models.BooleanField(default=False)),
                ("email_newsletter", models.BooleanField(default=False)),
                ("push_booking_updates", models.BooleanField(default=True)),
                ("push_payment_updates", models.BooleanField(default=True)),
                ("push_price_alerts", models.BooleanField(default=True)),
                ("push_itinerary_updates", models.BooleanField(default=False)),
                ("push_promotional", models.BooleanField(default=False)),
                ("sms_booking_updates", models.BooleanField(default=False)),
                ("sms_payment_updates", models.BooleanField(default=False)),
                ("sms_price_alerts", models.BooleanField(default=False)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("never", "Never"),
                        ],
                        default="realtime",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking Update"),
                            ("payment", "Payment"),
                            ("price_alert", "Price Alert"),
                            ("itinerary", "Itinerary"),
                            ("review", "Review"),
                            ("system", "System"),
                            ("promotional", "Promotional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_email", models.BooleanField(default=False)),
                ("sent_push", models.BooleanField(default=False)),
                ("sent_sms", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                ],
            },
        ),
    ]
