# Generated by Django 5.0.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="community/media/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("is_approved", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination Media",
                "verbose_name_plural": "Destination Media",
                "db_table": "community_destination_media",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="destinationmedia",
            index=models.Index(
                fields=["destination", "-created_at"],
                name="community_d_destina_idx_1",
            ),
        ),
        migrations.AddIndex(
            model_name="destinationmedia",
            index=models.Index(
                fields=["user", "-created_at"],
                name="community_d_user_id_idx_1",
            ),
        ),
        migrations.AddIndex(
            model_name="destinationmedia",
            index=models.Index(
                fields=["media_type"],
                name="community_d_media_t_idx_1",
            ),
        ),
        migrations.CreateModel(
            name="TravelStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("translated_content", models.TextField(blank=True)),
                ("cover_image", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Story",
                "verbose_name_plural": "Travel Stories",
                "db_table": "community_travel_stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="travelstory",
            index=models.Index(
                fields=["destination", "-created_at"],
                name="community_t_destina_idx_2",
            ),
        ),
        migrations.AddIndex(
            model_name="travelstory",
            index=models.Index(
                fields=["user", "-created_at"],
                name="community_t_user_id_idx_2",
            ),
        ),
        migrations.AddIndex(
            model_name="travelstory",
            index=models.Index(
                fields=["language"],
                name="community_t_languag_idx_1",
            ),
        ),
        migrations.CreateModel(
            name="TravelTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("money_saving", "Money Saving"),
                            ("safety", "Safety"),
                            ("food", "Food"),
                            ("transport", "Transport"),
                            ("culture", "Culture"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Tip",
                "verbose_name_plural": "Travel Tips",
                "db_table": "community_travel_tips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="traveltip",
            index=models.Index(
                fields=["destination", "-created_at"],
                name="community_tt_destina_idx_1",
            ),
        ),
        migrations.AddIndex(
            model_name="traveltip",
            index=models.Index(
                fields=["user", "-created_at"],
                name="community_tt_user_id_idx_1",
            ),
        ),
        migrations.AddIndex(
            model_name="traveltip",
            index=models.Index(
                fields=["category"],
                name="community_tt_catego_idx_1",
            ),
        ),
        migrations.CreateModel(
            name="DestinationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("country", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("history", models.TextField(blank=True)),
                ("culture", models.TextField(blank=True)),
                ("customs_etiquette", models.TextField(blank=True)),
                ("dress_code", models.TextField(blank=True)),
                ("religion_info", models.TextField(blank=True)),
                ("festivals", models.JSONField(default=list)),
                ("local_language", models.CharField(blank=True, max_length=100)),
                ("common_phrases", models.JSONField(default=dict)),
                ("currency", models.CharField(blank=True, max_length=50)),
                ("emergency_numbers", models.JSONField(default=dict)),
                ("official_tourism_url", models.URLField(blank=True)),
                ("ai_generated", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Destination Info",
                "verbose_name_plural": "Destination Info",
                "db_table": "community_destination_info",
                "ordering": ["destination"],
            },
        ),
        migrations.CreateModel(
            name="CuratedGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                (
                    "guide_type",
                    models.CharField(
                        choices=[
                            ("must_visit", "Must Visit"),
                            ("must_eat", "Must Eat"),
                            ("must_see", "Must See"),
                            ("must_do", "Must Do"),
                            ("hidden_gem", "Hidden Gem"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text=(
                            "Array of {name, description, rating, price_range, "
                            "best_time, address, website_url, image_url, tags}"
                        ),
                    ),
                ),
                ("ai_generated", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Curated Guide",
                "verbose_name_plural": "Curated Guides",
                "db_table": "community_curated_guides",
                "ordering": ["destination", "guide_type"],
                "unique_together": {("destination", "guide_type")},
            },
        ),
    ]
