# Generated by Django 5.2.12 on 2026-04-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="destinationmedia",
            new_name="community_d_destina_d9865f_idx",
            old_name="community_d_destina_idx_1",
        ),
        migrations.RenameIndex(
            model_name="destinationmedia",
            new_name="community_d_user_id_66129f_idx",
            old_name="community_d_user_id_idx_1",
        ),
        migrations.RenameIndex(
            model_name="destinationmedia",
            new_name="community_d_media_t_45683a_idx",
            old_name="community_d_media_t_idx_1",
        ),
        migrations.RenameIndex(
            model_name="travelstory",
            new_name="community_t_destina_c89cd8_idx",
            old_name="community_t_destina_idx_2",
        ),
        migrations.RenameIndex(
            model_name="travelstory",
            new_name="community_t_user_id_9e6486_idx",
            old_name="community_t_user_id_idx_2",
        ),
        migrations.RenameIndex(
            model_name="travelstory",
            new_name="community_t_languag_745208_idx",
            old_name="community_t_languag_idx_1",
        ),
        migrations.RenameIndex(
            model_name="traveltip",
            new_name="community_t_destina_8f66e0_idx",
            old_name="community_tt_destina_idx_1",
        ),
        migrations.RenameIndex(
            model_name="traveltip",
            new_name="community_t_user_id_6af71d_idx",
            old_name="community_tt_user_id_idx_1",
        ),
        migrations.RenameIndex(
            model_name="traveltip",
            new_name="community_t_categor_50d218_idx",
            old_name="community_tt_catego_idx_1",
        ),
    ]
