# Generated by Django 5.2.12 on 2026-04-11 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthAdvisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("vaccination_requirements", models.JSONField(default=list)),
                ("health_risks", models.JSONField(default=list)),
                (
                    "water_safety",
                    models.CharField(
                        choices=[
                            ("safe", "Safe to Drink"),
                            ("boil", "Boil Before Drinking"),
                            ("bottled_only", "Bottled Water Only"),
                            ("unsafe", "Unsafe"),
                        ],
                        max_length=15,
                    ),
                ),
                ("altitude_info", models.TextField(blank=True)),
                (
                    "medical_facilities_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("health_insurance_required", models.BooleanField(default=False)),
                ("emergency_numbers", models.JSONField(default=dict)),
                ("nearby_hospitals", models.JSONField(default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Health Advisory",
                "verbose_name_plural": "Health Advisories",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="SafetyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("country", models.CharField(max_length=100)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("weather", "Weather"),
                            ("political", "Political"),
                            ("health", "Health"),
                            ("crime", "Crime"),
                            ("natural_disaster", "Natural Disaster"),
                            ("travel_advisory", "Travel Advisory"),
                            ("terrorism", "Terrorism"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("source", models.CharField(blank=True, max_length=200)),
                ("source_url", models.URLField(blank=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Safety Alert",
                "verbose_name_plural": "Safety Alerts",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("country", models.CharField(max_length=100)),
                (
                    "overall_risk_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "crime_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "health_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "natural_disaster_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "political_stability_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "terrorism_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField()),
                ("recommendations", models.JSONField(default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("ai_generated", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Risk Assessment",
                "verbose_name_plural": "Risk Assessments",
                "ordering": ["-last_updated"],
                "unique_together": {("destination", "country")},
            },
        ),
    ]
