# Generated by Django 5.0.1 on 2026-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="travelhistory",
            new_name="travel_hist_user_id_866087_idx",
            old_name="travel_hist_user_id_b68d93_idx",
        ),
        migrations.RenameIndex(
            model_name="travelhistory",
            new_name="travel_hist_destina_309833_idx",
            old_name="travel_hist_destina_c6b8a2_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
