# Generated by Django 5.2.12 on 2026-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_rename_travel_hist_user_id_b68d93_idx_travel_hist_user_id_866087_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
