# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("orchestrator", "Orchestrator Agent"),
                            ("flight_search", "Flight Search Agent"),
                            ("hotel_search", "Hotel Search Agent"),
                            ("car_rental", "Car Rental Agent"),
                            ("itinerary_planner", "Itinerary Planner Agent"),
                            ("booking", "Booking Agent"),
                            ("recommendation", "Recommendation Agent"),
                            ("customer_support", "Customer Support Agent"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("agent_config", models.JSONField(blank=True, default=dict)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.IntegerField(default=0)),
                ("execution_time_ms", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("tools_called", models.JSONField(blank=True, default=list)),
                ("function_calls", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Execution",
                "verbose_name_plural": "Agent Executions",
                "db_table": "agent_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("conversation_context", models.JSONField(blank=True, default=dict)),
                ("user_intent", models.TextField(blank=True)),
                ("detected_entities", models.JSONField(blank=True, default=dict)),
                ("total_executions", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Session",
                "verbose_name_plural": "Agent Sessions",
                "db_table": "agent_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("log_data", models.JSONField(blank=True, default=dict)),
                ("agent_type", models.CharField(blank=True, max_length=50)),
                ("function_name", models.CharField(blank=True, max_length=200)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("exception_type", models.CharField(blank=True, max_length=200)),
                ("exception_traceback", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="agents.agentexecution",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="agents.agentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Log",
                "verbose_name_plural": "Agent Logs",
                "db_table": "agent_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="agents.agentsession",
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["user", "-started_at"], name="agent_sessi_user_id_6a614a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["status", "-started_at"], name="agent_sessi_status_4ac620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["session_id"], name="agent_sessi_session_43a358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentlog",
            index=models.Index(
                fields=["session", "-timestamp"], name="agent_logs_session_d4f920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentlog",
            index=models.Index(
                fields=["execution", "-timestamp"], name="agent_logs_executi_2755fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentlog",
            index=models.Index(
                fields=["log_level", "-timestamp"], name="agent_logs_log_lev_e77a11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["session", "-started_at"], name="agent_execu_session_f77fd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["agent_type", "-started_at"],
                name="agent_execu_agent_t_7a5194_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["status"], name="agent_execu_status_28c835_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["execution_id"], name="agent_execu_executi_6a8be5_idx"
            ),
        ),
    ]
