# Generated by Django 5.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_add_rag_document_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ragdocument",
            new_name="rag_documen_uploade_84f4bf_idx",
            old_name="rag_documents_uploade_c1a2b3_idx",
        ),
        migrations.RenameIndex(
            model_name="ragdocument",
            new_name="rag_documen_status_71a194_idx",
            old_name="rag_documents_status_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="ragdocument",
            new_name="rag_documen_scope_6a2018_idx",
            old_name="rag_documents_scope_a7b8c9_idx",
        ),
    ]
