# Generated by Django 5.2.12 on 2026-04-11 04:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_commercialization_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthInsuranceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, unique=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "recommended_coverage",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["emergency_evacuation","hospitalization","dental"]',
                    ),
                ),
                (
                    "avg_hospital_cost_per_day_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("public_healthcare_available", models.BooleanField(default=False)),
                (
                    "reciprocal_agreements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Countries with reciprocal health agreements",
                    ),
                ),
                ("emergency_number", models.CharField(default="112", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "vaccination_requirements",
                    models.JSONField(blank=True, default=list),
                ),
                ("malaria_risk", models.BooleanField(default=False)),
                ("altitude_risk", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Health insurance info",
                "db_table": "health_insurance_info",
            },
        ),
        migrations.AddField(
            model_name="userpreference",
            name="dietary_allergies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of food allergies, e.g. ["peanuts", "shellfish"]',
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="dietary_preference",
            field=models.CharField(
                choices=[
                    ("none", "No Restrictions"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("halal", "Halal"),
                    ("kosher", "Kosher"),
                    ("gluten_free", "Gluten Free"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="faith",
            field=models.CharField(
                choices=[
                    ("none", "Not Specified"),
                    ("islam", "Islam"),
                    ("christianity", "Christianity"),
                    ("judaism", "Judaism"),
                    ("hinduism", "Hinduism"),
                    ("buddhism", "Buddhism"),
                    ("sikhism", "Sikhism"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="faith_site_interest",
            field=models.BooleanField(
                default=False,
                help_text="Show mosques, temples, churches near itinerary stops",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="health_conditions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of health conditions to consider, e.g. ["asthma", "diabetes"]',
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="languages_spoken",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Languages the user speaks, e.g. ["en", "es", "fr"]',
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="max_activities_per_day",
            field=models.IntegerField(
                default=5, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="max_walking_km_per_day",
            field=models.DecimalField(
                decimal_places=1,
                default=10.0,
                help_text="Maximum comfortable walking distance in km per day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="medications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Medications with timezone adjustment needs",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="mobility",
            field=models.CharField(
                choices=[
                    ("full", "Full Mobility"),
                    ("limited", "Limited Mobility"),
                    ("wheelchair", "Wheelchair"),
                    ("elderly", "Elderly-Friendly"),
                ],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="pace",
            field=models.CharField(
                choices=[
                    ("slow", "Slow Traveler"),
                    ("moderate", "Moderate"),
                    ("packed", "Packed Schedule"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="prayer_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="affiliateclick",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="agentanalytics",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="agenttask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="collaborationvote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="collaborationvote",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("flight", "Flight"),
                    ("hotel", "Hotel"),
                    ("rental", "Vacation Rental"),
                    ("restaurant", "Restaurant"),
                    ("attraction", "Attraction"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pricewatch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pricewatch",
            name="watch_type",
            field=models.CharField(
                choices=[
                    ("flight", "Flight"),
                    ("hotel", "Hotel"),
                    ("rental", "Vacation Rental"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tripcollaboration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tripcollaborator",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="DestinationKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("continent", models.CharField(blank=True, max_length=50)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="AI-generated overview"),
                ),
                ("history", models.TextField(blank=True)),
                ("culture", models.TextField(blank=True)),
                ("heritage_sites", models.JSONField(blank=True, default=list)),
                (
                    "festivals",
                    models.JSONField(
                        blank=True, default=list, help_text="Major festivals with dates"
                    ),
                ),
                (
                    "customs",
                    models.JSONField(
                        blank=True, default=list, help_text="Local customs and norms"
                    ),
                ),
                ("best_months", models.JSONField(blank=True, default=list)),
                ("languages_spoken", models.JSONField(blank=True, default=list)),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("timezone_info", models.CharField(blank=True, max_length=50)),
                ("official_tourism_url", models.URLField(blank=True)),
                ("emergency_numbers", models.JSONField(blank=True, default=dict)),
                ("visa_info", models.TextField(blank=True)),
                ("ai_generated", models.BooleanField(default=True)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Destination Knowledge",
                "db_table": "destination_knowledge",
                "ordering": ["-views_count"],
                "indexes": [
                    models.Index(fields=["country"], name="dest_knowledge_country_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("name", models.CharField(max_length=300)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("pharmacy", "Pharmacy"),
                            ("emergency", "Emergency Room"),
                            ("dental", "Dental Clinic"),
                            ("specialist", "Specialist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("emergency_24h", models.BooleanField(default=False)),
                ("english_speaking", models.BooleanField(default=False)),
                ("accepts_travel_insurance", models.BooleanField(default=False)),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("operating_hours", models.JSONField(blank=True, default=dict)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("wheelchair_accessible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Medical facilities",
                "db_table": "medical_facilities",
                "indexes": [
                    models.Index(
                        fields=["destination", "facility_type"],
                        name="medical_dest_type_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("attraction", "Attraction"),
                            ("tour", "Tour Operator"),
                            ("transport", "Transport"),
                            ("shopping", "Shopping"),
                            ("spa", "Spa & Wellness"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "destination",
                    models.CharField(
                        db_index=True, help_text="City or region", max_length=200
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Revenue share % when AI saves money",
                        max_digits=5,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("total_coupons_redeemed", models.IntegerField(default=0)),
                (
                    "total_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "onboarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarded_partners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Partner Businesses",
                "db_table": "partner_businesses",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Off"),
                            ("fixed", "Fixed Amount Off"),
                            ("bogo", "Buy One Get One"),
                            ("freebie", "Free Item/Service"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage or fixed amount",
                        max_digits=10,
                    ),
                ),
                (
                    "min_spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum spend to use coupon",
                        max_digits=10,
                    ),
                ),
                ("max_uses", models.IntegerField(default=0, help_text="0 = unlimited")),
                ("times_used", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "terms",
                    models.TextField(blank=True, help_text="Terms and conditions"),
                ),
                (
                    "qr_data",
                    models.TextField(
                        blank=True, help_text="QR code data for in-store redemption"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="agents.partnerbusiness",
                    ),
                ),
            ],
            options={
                "db_table": "partner_coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "savings_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "order_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="agents.partnercoupon",
                    ),
                ),
            ],
            options={
                "db_table": "coupon_redemptions",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerTimeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("date", models.DateField()),
                ("fajr", models.CharField(max_length=10)),
                ("sunrise", models.CharField(max_length=10)),
                ("dhuhr", models.CharField(max_length=10)),
                ("asr", models.CharField(max_length=10)),
                ("maghrib", models.CharField(max_length=10)),
                ("isha", models.CharField(max_length=10)),
                (
                    "method",
                    models.CharField(
                        default="ISNA", help_text="Calculation method", max_length=50
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "prayer_time_cache",
                "indexes": [
                    models.Index(
                        fields=["destination", "date"], name="prayer_dest_date_idx"
                    )
                ],
                "unique_together": {("destination", "date", "method")},
            },
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("total_referrals", models.IntegerField(default=0)),
                ("successful_referrals", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "referral_codes",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed_up", "Signed Up"),
                            ("converted", "Converted"),
                            ("rewarded", "Rewarded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("referred_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="agents.referralcode",
                    ),
                ),
            ],
            options={
                "db_table": "referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpiritualSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("name", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pilgrimage", "Pilgrimage Site"),
                            ("heritage", "Religious Heritage"),
                            ("meditation", "Meditation / Retreat"),
                            ("festival_venue", "Festival Venue"),
                            ("sacred_natural", "Sacred Natural Site"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "faiths",
                    models.JSONField(
                        default=list,
                        help_text='Relevant faiths e.g. ["hinduism","buddhism"]',
                    ),
                ),
                ("description", models.TextField()),
                ("significance", models.TextField(blank=True, default="")),
                ("visitor_tips", models.TextField(blank=True, default="")),
                (
                    "dress_code",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "best_time_to_visit",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="")),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "spiritual_sites",
                "indexes": [
                    models.Index(
                        fields=["destination", "category"],
                        name="spiritual_dest_cat_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TravelStoryGenerated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itinerary_id",
                    models.IntegerField(
                        blank=True, help_text="Source itinerary ID", null=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField(help_text="AI-generated narrative")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("journal", "Daily Journal"),
                            ("instagram", "Instagram Story"),
                            ("blog", "Blog Post"),
                            ("social", "Social Media Post"),
                            ("thread", "Twitter/X Thread"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("cover_image_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "story_cards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of {day, title, content, mood, image_url}",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "travel_stories_generated",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="agents.travelstorygenerated",
                    ),
                ),
            ],
            options={
                "db_table": "story_likes",
            },
        ),
        migrations.CreateModel(
            name="StoryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="agents.travelstorygenerated",
                    ),
                ),
            ],
            options={
                "db_table": "story_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("trip_date", models.DateField(blank=True, null=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("loved", "Loved"),
                            ("liked", "Liked"),
                            ("neutral", "Neutral"),
                            ("disliked", "Disliked"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        blank=True, default=list, help_text="Things the user loved"
                    ),
                ),
                (
                    "lowlights",
                    models.JSONField(
                        blank=True, default=list, help_text="Things the user disliked"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["beach", "food", "history"]',
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("travel_style_used", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "rating",
                    models.IntegerField(default=0, help_text="1-5 overall rating"),
                ),
                (
                    "ai_insights",
                    models.JSONField(
                        blank=True, default=dict, help_text="AI analysis of the trip"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Memory",
                "verbose_name_plural": "Trip Memories",
                "db_table": "trip_memories",
                "ordering": ["-trip_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("duration_days", models.IntegerField(default=1)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("adventure", "Adventure"),
                            ("luxury", "Luxury"),
                            ("budget", "Budget"),
                            ("cultural", "Cultural"),
                            ("romantic", "Romantic"),
                            ("family", "Family"),
                            ("solo", "Solo"),
                            ("foodie", "Foodie"),
                            ("spiritual", "Spiritual"),
                            ("nature", "Nature"),
                        ],
                        default="adventure",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("cover_image_url", models.URLField(blank=True)),
                (
                    "itinerary_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of {day, activities: [{time, title, description, category, cost}]}",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "highlights",
                    models.JSONField(
                        blank=True, default=list, help_text="Top 3-5 highlights"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified influencer template"
                    ),
                ),
                ("clone_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trip_templates",
                "ordering": ["-clone_count", "-likes_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itinerary_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Created itinerary ID from the clone",
                        null=True,
                    ),
                ),
                (
                    "customizations",
                    models.JSONField(
                        blank=True, default=dict, help_text="Changes the user made"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloned_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clones",
                        to="agents.triptemplate",
                    ),
                ),
            ],
            options={
                "db_table": "template_clones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDestinationTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. food, transport, safety",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                (
                    "ai_moderation_score",
                    models.FloatField(default=0, help_text="AI quality score 0-1"),
                ),
                ("ai_moderation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tips",
                        to="agents.destinationknowledge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_destination_tips",
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorshipPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("name", models.CharField(max_length=300)),
                (
                    "worship_type",
                    models.CharField(
                        choices=[
                            ("mosque", "Mosque"),
                            ("church", "Church"),
                            ("synagogue", "Synagogue"),
                            ("temple", "Temple"),
                            ("gurdwara", "Gurdwara"),
                            ("monastery", "Monastery"),
                            ("shrine", "Shrine"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "faith",
                    models.CharField(
                        choices=[
                            ("islam", "Islam"),
                            ("christianity", "Christianity"),
                            ("judaism", "Judaism"),
                            ("hinduism", "Hinduism"),
                            ("buddhism", "Buddhism"),
                            ("sikhism", "Sikhism"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Available services e.g. ["friday_prayer","sunday_mass"]',
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["wudu_facility","parking","wheelchair_access"]',
                    ),
                ),
                ("operating_hours", models.JSONField(blank=True, default=dict)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("halal_food_nearby", models.BooleanField(default=False)),
                ("kosher_food_nearby", models.BooleanField(default=False)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "worship_places",
                "indexes": [
                    models.Index(
                        fields=["destination", "faith"], name="worship_dest_faith_idx"
                    ),
                    models.Index(fields=["worship_type"], name="worship_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("venue_name", models.CharField(max_length=300)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("attraction", "Tourist Attraction"),
                            ("transport", "Transport Hub"),
                            ("worship", "Place of Worship"),
                            ("medical", "Medical Facility"),
                            ("shopping", "Shopping"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mobility_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Not Accessible"),
                            (2, "Limited Access"),
                            (3, "Partially Accessible"),
                            (4, "Mostly Accessible"),
                            (5, "Fully Accessible"),
                        ]
                    ),
                ),
                ("wheelchair_accessible", models.BooleanField(default=False)),
                ("elevator_available", models.BooleanField(default=False)),
                ("accessible_restroom", models.BooleanField(default=False)),
                ("braille_signage", models.BooleanField(default=False)),
                ("hearing_loop", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accessibility_ratings",
                "indexes": [
                    models.Index(
                        fields=["destination", "venue_type"],
                        name="access_dest_venue_idx",
                    )
                ],
                "unique_together": {("user", "destination", "venue_name")},
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(db_index=True, max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("story", "Story"),
                            ("tip", "Tip"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "media_url",
                    models.URLField(blank=True, help_text="Photo/video/audio URL"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Text content for stories/tips"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_moderation_score", models.FloatField(default=0)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_items",
                "ordering": ["-upvotes", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["destination", "content_type", "status"],
                        name="content_dest_type_idx",
                    ),
                    models.Index(fields=["user"], name="content_user_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CulturalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dress_code", "Dress Code"),
                            ("tipping", "Tipping Etiquette"),
                            ("greetings", "Greetings & Gestures"),
                            ("dining", "Dining Etiquette"),
                            ("religious", "Religious Customs"),
                            ("business", "Business Etiquette"),
                            ("photography", "Photography Rules"),
                            ("laws", "Local Laws & Regulations"),
                            ("taboos", "Cultural Taboos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("advisory", "Advisory"),
                            ("important", "Important"),
                            ("critical", "Critical"),
                        ],
                        default="advisory",
                        max_length=20,
                    ),
                ),
                ("ai_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultural_info",
                        to="agents.destinationknowledge",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cultural Info",
                "db_table": "cultural_info",
                "ordering": ["category", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["destination", "category"], name="cultural_dest_cat_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=200)),
                ("dosage", models.CharField(blank=True, default="", max_length=100)),
                (
                    "home_time",
                    models.TimeField(
                        help_text="Time to take medication in home timezone"
                    ),
                ),
                ("home_timezone", models.CharField(max_length=60)),
                (
                    "frequency",
                    models.CharField(
                        default="daily",
                        help_text="e.g. daily, twice_daily, weekly",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "medication_reminders",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="med_user_active_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="partnerbusiness",
            index=models.Index(
                fields=["category", "destination"], name="partner_cat_dest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerbusiness",
            index=models.Index(fields=["status"], name="partner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="partnercoupon",
            index=models.Index(
                fields=["partner", "is_active"], name="coupon_partner_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercoupon",
            index=models.Index(fields=["valid_until"], name="coupon_valid_until_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(
                fields=["user", "-redeemed_at"], name="redemption_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer", "status"], name="referral_referrer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="travelstorygenerated",
            index=models.Index(
                fields=["user", "-created_at"], name="gen_story_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="travelstorygenerated",
            index=models.Index(fields=["destination"], name="gen_story_dest_idx"),
        ),
        migrations.AddIndex(
            model_name="travelstorygenerated",
            index=models.Index(fields=["share_token"], name="gen_story_token_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="storylike",
            unique_together={("user", "story")},
        ),
        migrations.AddIndex(
            model_name="tripmemory",
            index=models.Index(
                fields=["user", "-trip_date"], name="trip_mem_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripmemory",
            index=models.Index(fields=["destination"], name="trip_mem_dest_idx"),
        ),
        migrations.AddIndex(
            model_name="tripmemory",
            index=models.Index(fields=["sentiment"], name="trip_mem_sentiment_idx"),
        ),
        migrations.AddIndex(
            model_name="triptemplate",
            index=models.Index(fields=["destination"], name="template_dest_idx"),
        ),
        migrations.AddIndex(
            model_name="triptemplate",
            index=models.Index(fields=["style"], name="template_style_idx"),
        ),
        migrations.AddIndex(
            model_name="triptemplate",
            index=models.Index(fields=["creator"], name="template_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="triptemplate",
            index=models.Index(fields=["-clone_count"], name="template_clones_idx"),
        ),
        migrations.AddIndex(
            model_name="userdestinationtip",
            index=models.Index(
                fields=["destination", "status"], name="user_tip_dest_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdestinationtip",
            index=models.Index(fields=["user"], name="user_tip_user_idx"),
        ),
    ]
