# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Cuisine",
                "verbose_name_plural": "Cuisines",
                "db_table": "cuisines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("address", models.TextField()),
                ("city", models.CharField(db_index=True, max_length=200)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("$", "Budget ($)"),
                            ("$$", "Moderate ($$)"),
                            ("$$$", "Upscale ($$$)"),
                            ("$$$$", "Fine Dining ($$$$)"),
                        ],
                        default="$$",
                        max_length=5,
                    ),
                ),
                (
                    "average_cost_per_person",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("seating_capacity", models.IntegerField(blank=True, null=True)),
                ("has_outdoor_seating", models.BooleanField(default=False)),
                ("has_delivery", models.BooleanField(default=False)),
                ("has_takeout", models.BooleanField(default=False)),
                ("has_reservation", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("is_wheelchair_accessible", models.BooleanField(default=False)),
                ("dietary_options", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("primary_image", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("menu_url", models.URLField(blank=True)),
                ("reservation_url", models.URLField(blank=True)),
                ("delivery_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cuisines",
                    models.ManyToManyField(
                        related_name="restaurants", to="restaurants.cuisine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "db_table": "restaurants",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_reference", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reservation_date", models.DateField()),
                ("reservation_time", models.TimeField()),
                (
                    "number_of_guests",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(max_length=20)),
                ("special_requests", models.TextField(blank=True)),
                ("seating_preference", models.CharField(blank=True, max_length=100)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant Booking",
                "verbose_name_plural": "Restaurant Bookings",
                "db_table": "restaurant_bookings",
                "ordering": ["-reservation_date", "-reservation_time"],
            },
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["city", "country"], name="restaurants_city_a80d4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["price_range"], name="restaurants_price_r_eaa8f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["-rating"], name="restaurants_rating_422bd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantbooking",
            index=models.Index(
                fields=["user", "-reservation_date"],
                name="restaurant__user_id_ae3b56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantbooking",
            index=models.Index(
                fields=["restaurant", "reservation_date"],
                name="restaurant__restaur_0fba85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantbooking",
            index=models.Index(fields=["status"], name="restaurant__status_62f1dd_idx"),
        ),
    ]
