# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(db_index=True, max_length=20)),
                ("airline_code", models.CharField(max_length=3)),
                ("airline_name", models.CharField(max_length=200)),
                ("origin_airport", models.CharField(db_index=True, max_length=3)),
                ("origin_city", models.CharField(max_length=200)),
                ("origin_country", models.CharField(max_length=100)),
                ("destination_airport", models.CharField(db_index=True, max_length=3)),
                ("destination_city", models.CharField(max_length=200)),
                ("destination_country", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField(db_index=True)),
                ("arrival_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("aircraft_type", models.CharField(blank=True, max_length=50)),
                ("aircraft_model", models.CharField(blank=True, max_length=100)),
                (
                    "travel_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business"),
                            ("first", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("delayed", "Delayed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("total_seats", models.IntegerField(default=0)),
                ("available_seats", models.IntegerField(default=0)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_meals", models.BooleanField(default=False)),
                ("has_entertainment", models.BooleanField(default=False)),
                ("baggage_allowance_kg", models.IntegerField(default=23)),
                ("carry_on_allowance_kg", models.IntegerField(default=7)),
                ("is_direct", models.BooleanField(db_index=True, default=True)),
                ("stops_count", models.IntegerField(default=0)),
                ("layover_airports", models.JSONField(blank=True, default=list)),
                ("booking_url", models.URLField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flight",
                "verbose_name_plural": "Flights",
                "db_table": "flights",
                "ordering": ["departure_time"],
                "indexes": [
                    models.Index(
                        fields=[
                            "origin_airport",
                            "destination_airport",
                            "departure_time",
                        ],
                        name="flights_origin__a54535_idx",
                    ),
                    models.Index(
                        fields=["airline_code", "flight_number"],
                        name="flights_airline_bbe4fd_idx",
                    ),
                    models.Index(
                        fields=["status", "departure_time"],
                        name="flights_status_b041c2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FlightSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_airport", models.CharField(max_length=3)),
                ("origin_city", models.CharField(blank=True, max_length=200)),
                ("destination_airport", models.CharField(max_length=3)),
                ("destination_city", models.CharField(blank=True, max_length=200)),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("one_way", "One Way"),
                            ("round_trip", "Round Trip"),
                            ("multi_city", "Multi City"),
                        ],
                        default="round_trip",
                        max_length=20,
                    ),
                ),
                (
                    "adults",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "children",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "infants",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("preferred_class", models.CharField(default="economy", max_length=20)),
                ("direct_flights_only", models.BooleanField(default=False)),
                ("preferred_airlines", models.JSONField(blank=True, default=list)),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("search_duration_ms", models.IntegerField(default=0)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Search",
                "verbose_name_plural": "Flight Searches",
                "db_table": "flight_searches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="flight_sear_user_id_2d1b64_idx",
                    ),
                    models.Index(
                        fields=["origin_airport", "destination_airport"],
                        name="flight_sear_origin__f10dff_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="flight_sear_created_99b28a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_airport", models.CharField(max_length=3)),
                ("destination_airport", models.CharField(max_length=3)),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("travel_class", models.CharField(default="economy", max_length=20)),
                ("preferred_airlines", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lowest_price_seen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("email_notification", models.BooleanField(default=True)),
                ("push_notification", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
                "db_table": "price_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="price_alert_user_id_82c832_idx"
                    ),
                    models.Index(
                        fields=["status", "expiry_date"],
                        name="price_alert_status_82157f_idx",
                    ),
                    models.Index(
                        fields=["origin_airport", "destination_airport"],
                        name="price_alert_origin__17655e_idx",
                    ),
                ],
            },
        ),
    ]
