# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("destination", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("travelers", models.JSONField(blank=True, default=list)),
                ("number_of_travelers", models.IntegerField(default=1)),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_public", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=False)),
                ("shared_with", models.JSONField(blank=True, default=list)),
                ("cover_image", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary",
                "verbose_name_plural": "Itineraries",
                "db_table": "itineraries",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("date", models.DateField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("weather_temp_high", models.IntegerField(blank=True, null=True)),
                ("weather_temp_low", models.IntegerField(blank=True, null=True)),
                ("weather_condition", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="itineraries.itinerary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary Day",
                "verbose_name_plural": "Itinerary Days",
                "db_table": "itinerary_days",
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("attraction", "Attraction"),
                            ("activity", "Activity"),
                            ("transport", "Transportation"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("location_address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                ("booking_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="itineraries.itineraryday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary Item",
                "verbose_name_plural": "Itinerary Items",
                "db_table": "itinerary_items",
                "ordering": ["day", "start_time", "order"],
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(db_index=True, max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("temp_high", models.IntegerField()),
                ("temp_low", models.IntegerField()),
                ("temp_avg", models.IntegerField()),
                ("condition", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("humidity", models.IntegerField(blank=True, null=True)),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("precipitation_chance", models.IntegerField(blank=True, null=True)),
                ("uv_index", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(default="openweather", max_length=50)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weather",
                "verbose_name_plural": "Weather Forecasts",
                "db_table": "weather",
                "ordering": ["date"],
                "unique_together": {("location", "date", "source")},
            },
        ),
        migrations.AddIndex(
            model_name="itinerary",
            index=models.Index(
                fields=["user", "-start_date"], name="itineraries_user_id_7e72e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerary",
            index=models.Index(
                fields=["status", "-start_date"], name="itineraries_status_d60ed1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itineraryday",
            unique_together={("itinerary", "day_number")},
        ),
    ]
