# Generated by Django 5.2.12 on 2026-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0005_tripfeedback"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tripfeedback",
            new_name="trip_feedba_user_id_020a36_idx",
            old_name="trip_feedba_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="tripfeedback",
            new_name="trip_feedba_sentime_ca4871_idx",
            old_name="trip_feedba_sentime_idx",
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("flight", "Flight"),
                    ("hotel", "Hotel"),
                    ("rental", "Vacation Rental"),
                    ("restaurant", "Restaurant"),
                    ("attraction", "Attraction"),
                    ("activity", "Activity"),
                    ("transport", "Transportation"),
                    ("note", "Note"),
                ],
                max_length=20,
            ),
        ),
    ]
