# Generated by Django 5.2.12 on 2026-04-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "itineraries",
            "0006_rename_trip_feedba_user_id_idx_trip_feedba_user_id_020a36_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="confirmations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="owner_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="votes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
