# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("compact", "Compact"),
                            ("midsize", "Midsize"),
                            ("fullsize", "Full-size"),
                            ("suv", "SUV"),
                            ("luxury", "Luxury"),
                            ("van", "Van/Minivan"),
                            ("convertible", "Convertible"),
                            ("sports", "Sports Car"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("passenger_capacity", models.IntegerField(default=5)),
                ("luggage_capacity", models.IntegerField(default=2)),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                ("image", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Car Type",
                "verbose_name_plural": "Car Types",
                "db_table": "car_types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CarRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=50)),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                ("rental_company", models.CharField(max_length=200)),
                ("pickup_location", models.CharField(db_index=True, max_length=200)),
                ("pickup_address", models.TextField()),
                ("pickup_city", models.CharField(db_index=True, max_length=200)),
                ("pickup_country", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "insurance_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "additional_driver_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "young_driver_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("has_gps", models.BooleanField(default=False)),
                ("has_bluetooth", models.BooleanField(default=False)),
                ("has_air_conditioning", models.BooleanField(default=True)),
                ("minimum_age", models.IntegerField(default=21)),
                ("mileage_limit_per_day", models.IntegerField(blank=True, null=True)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("primary_image", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("maintenance", "Maintenance"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="car_rentals.cartype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Rental",
                "verbose_name_plural": "Car Rentals",
                "db_table": "car_rentals",
                "ordering": ["price_per_day"],
            },
        ),
        migrations.CreateModel(
            name="RentalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("pickup_date", models.DateTimeField()),
                ("return_date", models.DateTimeField()),
                ("total_days", models.IntegerField()),
                ("pickup_location", models.CharField(max_length=200)),
                ("return_location", models.CharField(max_length=200)),
                ("different_return_location", models.BooleanField(default=False)),
                ("driver_name", models.CharField(max_length=255)),
                ("driver_email", models.EmailField(max_length=254)),
                ("driver_phone", models.CharField(max_length=20)),
                ("driver_license_number", models.CharField(max_length=50)),
                ("driver_age", models.IntegerField()),
                ("additional_drivers", models.IntegerField(default=0)),
                ("includes_insurance", models.BooleanField(default=False)),
                ("special_requests", models.TextField(blank=True)),
                ("rental_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "insurance_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "additional_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "deposit_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("deposit_refunded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car_rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="car_rentals.carrental",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_rental_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental Booking",
                "verbose_name_plural": "Rental Bookings",
                "db_table": "rental_bookings",
                "ordering": ["-pickup_date"],
            },
        ),
        migrations.AddIndex(
            model_name="carrental",
            index=models.Index(
                fields=["pickup_city", "status"], name="car_rentals_pickup__2e7463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrental",
            index=models.Index(
                fields=["car_type", "status"], name="car_rentals_car_typ_89363e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["user", "-pickup_date"], name="rental_book_user_id_5d51b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["booking_reference"], name="rental_book_booking_90d8a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalbooking",
            index=models.Index(
                fields=["status", "-pickup_date"], name="rental_book_status_db6290_idx"
            ),
        ),
    ]
