from django.core.management.base import BaseCommand
from apps.hotels.models import Hotel


class Command(BaseCommand):
    help = 'Seed database with sample hotel data'

    def handle(self, *args, **options):
        self.stdout.write('Seeding hotel data...')

        hotels_data = [
            # Miami Hotels
            {
                'name': 'The Miami Beach EDITION',
                'chain': 'EDITION Hotels',
                'city': 'Miami',
                'state': 'Florida',
                'country': 'USA',
                'address': '2901 Collins Avenue',
                'zip_code': '33140',
                'latitude': 25.8048,
                'longitude': -80.1237,
                'star_rating': 5,
                'guest_rating': 9.2,
                'property_type': 'hotel',
                'price_range_min': 450,
                'price_range_max': 850,
                'total_rooms': 294,
                'description': 'Luxury beachfront hotel with stunning ocean views, multiple pools, and world-class dining.',
                'check_in_time': '16:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 786-257-4500',
                'email': 'reservations@editionmiami.com',
                'website': 'https://www.editionhotels.com',
                'is_featured': True,
                'is_active': True,
            },
            {
                'name': 'Fontainebleau Miami Beach',
                'chain': 'Fontainebleau',
                'city': 'Miami',
                'state': 'Florida',
                'country': 'USA',
                'address': '4441 Collins Avenue',
                'zip_code': '33140',
                'latitude': 25.8206,
                'longitude': -80.1228,
                'star_rating': 5,
                'guest_rating': 8.8,
                'property_type': 'resort',
                'price_range_min': 380,
                'price_range_max': 750,
                'total_rooms': 1504,
                'description': 'Iconic beachfront resort featuring 12 restaurants, nightlife, and expansive pools.',
                'check_in_time': '16:00:00',
                'check_out_time': '11:00:00',
                'phone': '+1 305-538-2000',
                'email': 'reservations@fontainebleau.com',
                'website': 'https://www.fontainebleau.com',
                'is_featured': True,
                'is_active': True,
            },
            {
                'name': 'W South Beach',
                'chain': 'W Hotels',
                'city': 'Miami',
                'state': 'Florida',
                'country': 'USA',
                'address': '2201 Collins Avenue',
                'zip_code': '33139',
                'latitude': 25.7935,
                'longitude': -80.1284,
                'star_rating': 5,
                'guest_rating': 8.5,
                'property_type': 'hotel',
                'price_range_min': 420,
                'price_range_max': 800,
                'total_rooms': 408,
                'description': 'Trendy beachfront hotel with contemporary design, multiple pools, and vibrant nightlife.',
                'check_in_time': '16:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 305-938-3000',
                'email': 'wsouthbeach@whotels.com',
                'website': 'https://www.marriott.com/wsob',
                'is_featured': True,
                'is_active': True,
            },
            {
                'name': 'The Betsy Hotel',
                'chain': 'Independent',
                'city': 'Miami',
                'state': 'Florida',
                'country': 'USA',
                'address': '1440 Ocean Drive',
                'zip_code': '33139',
                'latitude': 25.7867,
                'longitude': -80.1299,
                'star_rating': 4,
                'guest_rating': 9.0,
                'property_type': 'boutique',
                'price_range_min': 320,
                'price_range_max': 650,
                'total_rooms': 130,
                'description': 'Art Deco boutique hotel on Ocean Drive with rooftop pool and cultural programs.',
                'check_in_time': '15:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 305-531-6100',
                'email': 'reservations@thebetsyhotel.com',
                'website': 'https://www.thebetsyhotel.com',
                'is_featured': False,
                'is_active': True,
            },
            # New York Hotels
            {
                'name': 'The Plaza Hotel',
                'chain': 'Fairmont',
                'city': 'New York',
                'state': 'New York',
                'country': 'USA',
                'address': 'Fifth Avenue at Central Park South',
                'zip_code': '10019',
                'latitude': 40.7645,
                'longitude': -73.9744,
                'star_rating': 5,
                'guest_rating': 9.1,
                'property_type': 'hotel',
                'price_range_min': 595,
                'price_range_max': 1200,
                'total_rooms': 282,
                'description': 'Legendary luxury hotel overlooking Central Park with historic elegance.',
                'check_in_time': '16:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 212-759-3000',
                'email': 'reservations@theplazany.com',
                'website': 'https://www.fairmont.com/the-plaza',
                'is_featured': True,
                'is_active': True,
            },
            {
                'name': 'The St. Regis New York',
                'chain': 'St. Regis',
                'city': 'New York',
                'state': 'New York',
                'country': 'USA',
                'address': '2 East 55th Street',
                'zip_code': '10022',
                'latitude': 40.7619,
                'longitude': -73.9749,
                'star_rating': 5,
                'guest_rating': 8.9,
                'property_type': 'hotel',
                'price_range_min': 525,
                'price_range_max': 1100,
                'total_rooms': 238,
                'description': 'Iconic Beaux-Arts hotel with butler service and timeless luxury.',
                'check_in_time': '16:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 212-753-4500',
                'email': 'reservations@stregisnewyork.com',
                'website': 'https://www.marriott.com/stregis',
                'is_featured': True,
                'is_active': True,
            },
            # Los Angeles Hotels
            {
                'name': 'The Beverly Hills Hotel',
                'chain': 'Dorchester Collection',
                'city': 'Los Angeles',
                'state': 'California',
                'country': 'USA',
                'address': '9641 Sunset Boulevard',
                'zip_code': '90210',
                'latitude': 34.0799,
                'longitude': -118.4126,
                'star_rating': 5,
                'guest_rating': 9.3,
                'property_type': 'hotel',
                'price_range_min': 695,
                'price_range_max': 1500,
                'total_rooms': 210,
                'description': 'Legendary pink palace in Beverly Hills with Hollywood glamour.',
                'check_in_time': '15:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 310-276-2251',
                'email': 'reservations@beverlyhillshotel.com',
                'website': 'https://www.dorchestercollection.com',
                'is_featured': True,
                'is_active': True,
            },
            {
                'name': 'Shutters on the Beach',
                'chain': 'Independent',
                'city': 'Los Angeles',
                'state': 'California',
                'country': 'USA',
                'address': '1 Pico Boulevard',
                'zip_code': '90405',
                'latitude': 34.0073,
                'longitude': -118.4987,
                'star_rating': 5,
                'guest_rating': 8.7,
                'property_type': 'hotel',
                'price_range_min': 475,
                'price_range_max': 950,
                'total_rooms': 198,
                'description': 'Beach house elegance on Santa Monica Beach with ocean views.',
                'check_in_time': '16:00:00',
                'check_out_time': '12:00:00',
                'phone': '+1 310-458-0030',
                'email': 'reservations@shuttersonthebeach.com',
                'website': 'https://www.shuttersonthebeach.com',
                'is_featured': False,
                'is_active': True,
            },
        ]

        created_count = 0
        for hotel_data in hotels_data:
            hotel, created = Hotel.objects.get_or_create(
                name=hotel_data['name'],
                city=hotel_data['city'],
                defaults=hotel_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'✓ Created: {hotel.name} in {hotel.city}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'- Already exists: {hotel.name}')
                )

        self.stdout.write(
            self.style.SUCCESS(f'\n✅ Successfully seeded {created_count} hotels!')
        )
