# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttractionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="attractions.attractioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attraction Category",
                "verbose_name_plural": "Attraction Categories",
                "db_table": "attraction_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "attraction_type",
                    models.CharField(
                        choices=[
                            ("museum", "Museum"),
                            ("monument", "Monument"),
                            ("park", "Park"),
                            ("theme_park", "Theme Park"),
                            ("zoo", "Zoo"),
                            ("aquarium", "Aquarium"),
                            ("theater", "Theater"),
                            ("gallery", "Art Gallery"),
                            ("landmark", "Landmark"),
                            ("tour", "Tour"),
                            ("activity", "Activity"),
                            ("entertainment", "Entertainment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(db_index=True, max_length=200)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("is_open_24_7", models.BooleanField(default=False)),
                (
                    "admission_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "typical_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("primary_image", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("video_urls", models.JSONField(blank=True, default=list)),
                ("accessibility_features", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("languages_available", models.JSONField(blank=True, default=list)),
                ("booking_required", models.BooleanField(default=False)),
                ("booking_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="attractions", to="attractions.attractioncategory"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attraction",
                "verbose_name_plural": "Attractions",
                "db_table": "attractions",
                "ordering": ["-rating", "name"],
                "indexes": [
                    models.Index(
                        fields=["city", "country"], name="attractions_city_ebcd13_idx"
                    ),
                    models.Index(
                        fields=["attraction_type"],
                        name="attractions_attract_75e548_idx",
                    ),
                    models.Index(
                        fields=["-rating"], name="attractions_rating_b140a7_idx"
                    ),
                ],
            },
        ),
    ]
