# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("chain", models.CharField(blank=True, max_length=200)),
                ("brand", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(db_index=True, max_length=200)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "star_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Star"),
                            (3, "3 Star"),
                            (4, "4 Star"),
                            (5, "5 Star"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "guest_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("resort", "Resort"),
                            ("motel", "Motel"),
                            ("hostel", "Hostel"),
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("guesthouse", "Guesthouse"),
                        ],
                        default="hotel",
                        max_length=50,
                    ),
                ),
                ("total_rooms", models.IntegerField(default=0)),
                ("check_in_time", models.TimeField(default="15:00:00")),
                ("check_out_time", models.TimeField(default="11:00:00")),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("primary_image", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "price_range_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_range_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotels",
                "db_table": "hotels",
                "ordering": ["-guest_rating", "name"],
                "indexes": [
                    models.Index(
                        fields=["city", "country"], name="hotels_city_d0dfa4_idx"
                    ),
                    models.Index(
                        fields=["star_rating", "-guest_rating"],
                        name="hotels_star_ra_4b488d_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="hotels_is_acti_26732e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HotelAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("room", "Room"),
                            ("bathroom", "Bathroom"),
                            ("food_drink", "Food & Drink"),
                            ("services", "Services"),
                            ("entertainment", "Entertainment"),
                            ("business", "Business"),
                            ("wellness", "Wellness"),
                            ("outdoor", "Outdoor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "additional_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Amenity",
                "verbose_name_plural": "Hotel Amenities",
                "db_table": "hotel_amenities",
                "indexes": [
                    models.Index(
                        fields=["hotel", "category"],
                        name="hotel_ameni_hotel_i_4f395e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HotelSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("nights", models.IntegerField(default=1)),
                (
                    "rooms",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "adults",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "children",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_star_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "min_guest_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("property_types", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                (
                    "max_price_per_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("search_duration_ms", models.IntegerField(default=0)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Search",
                "verbose_name_plural": "Hotel Searches",
                "db_table": "hotel_searches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="hotel_searc_user_id_e8349b_idx",
                    ),
                    models.Index(
                        fields=["city", "-created_at"],
                        name="hotel_searc_city_64754a_idx",
                    ),
                ],
            },
        ),
    ]
