# Generated by Django 5.2.12 on 2026-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="bathrooms",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="bedrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="beds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="cancellation_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flexible", "Flexible"),
                    ("moderate", "Moderate"),
                    ("strict", "Strict"),
                    ("non_refundable", "Non-Refundable"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="cleaning_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="has_kitchen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="has_parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="has_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="has_washer_dryer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="host_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="hotel",
            name="host_response_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="house_rules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotel",
            name="is_entire_property",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="is_superhost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="max_guests",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="minimum_stay_nights",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="hotel",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("per_room", "Per Room Per Night"),
                    ("per_property", "Per Property Per Night"),
                ],
                default="per_room",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="service_fee_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="hotelsearch",
            name="entire_property_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotelsearch",
            name="include_hotels",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hotelsearch",
            name="include_rentals",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hotelsearch",
            name="min_bathrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotelsearch",
            name="min_bedrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotelsearch",
            name="pet_friendly_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("resort", "Resort"),
                    ("motel", "Motel"),
                    ("hostel", "Hostel"),
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("guesthouse", "Guesthouse"),
                    ("vacation_rental", "Vacation Rental"),
                    ("cabin", "Cabin"),
                    ("cottage", "Cottage"),
                    ("townhouse", "Townhouse"),
                    ("farmhouse", "Farmhouse"),
                ],
                default="hotel",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hotelamenity",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("room", "Room"),
                    ("bathroom", "Bathroom"),
                    ("food_drink", "Food & Drink"),
                    ("services", "Services"),
                    ("entertainment", "Entertainment"),
                    ("business", "Business"),
                    ("wellness", "Wellness"),
                    ("outdoor", "Outdoor"),
                    ("kitchen", "Kitchen"),
                    ("laundry", "Laundry"),
                    ("parking", "Parking & Access"),
                    ("safety", "Safety & Security"),
                ],
                max_length=20,
            ),
        ),
    ]
