# Generated by Django 5.0.1 on 2026-02-09 20:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Moderation"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("booking_reference", models.CharField(blank=True, max_length=100)),
                ("moderation_notes", models.TextField(blank=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("helpful_count", models.IntegerField(default=0)),
                ("not_helpful_count", models.IntegerField(default=0)),
                ("images", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("flight_comfort", "Comfort"),
                            ("flight_service", "Service"),
                            ("flight_food", "Food & Beverage"),
                            ("flight_entertainment", "Entertainment"),
                            ("flight_value", "Value for Money"),
                            ("hotel_cleanliness", "Cleanliness"),
                            ("hotel_comfort", "Comfort"),
                            ("hotel_location", "Location"),
                            ("hotel_facilities", "Facilities"),
                            ("hotel_staff", "Staff"),
                            ("hotel_value", "Value for Money"),
                            ("restaurant_food", "Food Quality"),
                            ("restaurant_service", "Service"),
                            ("restaurant_ambiance", "Ambiance"),
                            ("restaurant_value", "Value for Money"),
                            ("attraction_experience", "Experience"),
                            ("attraction_value", "Value for Money"),
                            ("attraction_organization", "Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "db_table": "ratings",
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["content_type", "object_id"], name="reviews_content_be5f25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="reviews_user_id_9f7b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["status", "-created_at"], name="reviews_status_f5992a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("review", "aspect")},
        ),
    ]
