# Generated by Django 5.2.12 on 2026-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("destination", "Destination"),
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("attraction", "Attraction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_name", models.CharField(db_index=True, max_length=255)),
                ("destination", models.CharField(db_index=True, max_length=200)),
                ("overall_score", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "safety_score",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "value_score",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "food_score",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "culture_score",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "accessibility_score",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                (
                    "community_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("summary", models.TextField()),
                ("pros", models.JSONField(default=list)),
                ("cons", models.JSONField(default=list)),
                ("best_for", models.JSONField(default=list)),
                ("enjoyment_factors", models.JSONField(default=dict)),
                ("ai_generated", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reviews_ai_rating",
                "ordering": ["-overall_score"],
                "unique_together": {("entity_type", "entity_name", "destination")},
            },
        ),
    ]
