# Generated by Django 5.0.1 on 2026-02-11 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttractionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Attraction Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TouristAttraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                (
                    "price_level",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("$", "Budget ($)"),
                            ("$$", "Moderate ($$)"),
                            ("$$$", "Expensive ($$$)"),
                            ("$$$$", "Very Expensive ($$$$)"),
                        ],
                        default="$",
                        max_length=10,
                    ),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("hours", models.CharField(blank=True, max_length=255)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("wheelchair_accessible", models.BooleanField(default=False)),
                ("family_friendly", models.BooleanField(default=True)),
                ("primary_image", models.URLField(blank=True)),
                ("thumbnail", models.URLField(blank=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("source", models.CharField(default="serp_api", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attractions",
                        to="tourist_attractions.attractioncategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-review_count"],
            },
        ),
        migrations.CreateModel(
            name="AttractionVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attraction_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="tourist_attractions.touristattraction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="touristattraction",
            index=models.Index(
                fields=["city", "category"], name="tourist_att_city_31ff56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="touristattraction",
            index=models.Index(fields=["rating"], name="tourist_att_rating_3cfa5b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attractionvisit",
            unique_together={("user", "attraction")},
        ),
    ]
